# Generated by Django 3.1.13 on 2022-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0009_update_user_input_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcollection',
            name='portfolio_category',
            field=models.CharField(choices=[('DATA SCIENCE', 'data science'), ('ANIMATION', 'animation'), ('PROGRAMMING LANGUAGES', 'programming languages'), ('MATHEMATICS', 'mathematics')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='workflowcollection',
            name='portfolio_description',
            field=models.TextField(default='PROGRAMMING LANGUAGES'),
            preserve_default=False,
        ),
    ]
