# Generated by Django 3.1.14 on 2022-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0011_workflowstepuserinput_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcollection',
            name='portfolio_category',
            field=models.CharField(blank=True, choices=[('DATA SCIENCE', 'data science'), ('ANIMATION', 'animation'), ('PROGRAMMING LANGUAGES', 'programming languages'), ('MATHEMATICS', 'mathematics')], default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='workflowcollection',
            name='portfolio_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
