# Generated by Django 3.1.13 on 2022-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0013_workflowstepanswerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepanswerimage',
            name='url',
            field=models.ImageField(max_length=200, null=True, upload_to='answer_options/'),
        ),
    ]
