# Generated by Django 3.1.13 on 2022-05-12 16:33

from django.db import migrations, models
import django_workflow_system.utils.media_files


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0015_update_user_input_types_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepuserinput',
            name='url',
            field=models.ImageField(max_length=200, null=True, upload_to=django_workflow_system.utils.media_files.workflow_step_media_location, verbose_name='Question Image'),
        ),
    ]
