# Generated by Django 3.1.14 on 2022-05-21 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0017_auto_20220518_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCollectionPortfolioCategory',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Workflow Collection Portfolio Categories',
                'db_table': 'workflow_system_collection_portfolio_category',
            },
        ),
        migrations.AlterField(
            model_name='workflowcollection',
            name='portfolio_category',
            field=models.ForeignKey(help_text="The category this workflow collection will be sorted into in a user's E-Portfolio", null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_workflow_system.workflowcollectionportfoliocategory'),
        ),
    ]
