# Generated by Django 3.1.14 on 2022-05-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0019_auto_20220520_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcollection',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, help_text="The category this workflow collection will be sorted into in a user's E-Portfolio", null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_workflow_system.workflowcollectionportfoliocategory', to_field='category'),
        ),
    ]
