# Generated by Django 3.1.13 on 2022-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0020_auto_20220520_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcollection',
            name='active_core',
            field=models.BooleanField(default=False, help_text='Indicates if collection is ready for use.'),
        ),
        migrations.AddField(
            model_name='workflowcollection',
            name='active_secondary',
            field=models.BooleanField(default=False, help_text='Indicates if collection is ready for use.'),
        ),
    ]
